/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace OpenFLModelHarness {
      
    export type InitParamsStruct = {participants: AddressLike[], reputations: BigNumberish[], roundReps: BigNumberish[], nrOfVotesOfUser: BigNumberish[], round: BigNumberish}

    export type InitParamsStructOutput = [participants: string[], reputations: bigint[], roundReps: bigint[], nrOfVotesOfUser: bigint[], round: bigint] & {participants: string[], reputations: bigint[], roundReps: bigint[], nrOfVotesOfUser: bigint[], round: bigint }
  
    }

  export interface OpenFLModelHarnessInterface extends Interface {
    getFunction(nameOrSignature: "__isPunished" | "__testInitSettleState" | "_getUserGRSAtAddress" | "_setUserGRSAtAddress" | "_setUserGRSAtAddressStorage" | "contributionScore" | "contributionStart" | "exitModel" | "feedback" | "freeriderPenalty" | "getAllAccuraciesAbout" | "getAllPreviousAccuraciesAndLosses" | "getUser" | "hasVoted" | "initTS" | "isContributionRoundDone" | "isFeedBackRoundDone" | "max_collateral" | "min_collateral" | "min_rounds" | "modelHash" | "nrOfContributionScores" | "nrOfParticipants" | "nrOfProvidedHashedWeights" | "participants" | "prev_accs" | "prev_losses" | "provideHashedWeights" | "punishfactor" | "punishfactorContrib" | "register()" | "register(address)" | "registerSlot" | "rewardLeft" | "rewardPerRound" | "round" | "roundStart" | "secretOf" | "settle" | "submitContributionScore" | "submitFeedbackBytes" | "submitFeedbackBytesAndAccuracies" | "testing" | "totalReward" | "users" | "votedPositiveFor" | "votesPerRound" | "weightsOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContributionScoreSubmitted" | "DebugUser" | "Disqualification" | "EndRound" | "FederatedLerningModelDeployed" | "Feedback" | "PassivPunishment" | "Punishment" | "Registered" | "Reward"): EventFragment;

    encodeFunctionData(functionFragment: '__isPunished', values: [AddressLike]): string;
encodeFunctionData(functionFragment: '__testInitSettleState', values: [OpenFLModelHarness.InitParamsStruct]): string;
encodeFunctionData(functionFragment: '_getUserGRSAtAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: '_setUserGRSAtAddress', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: '_setUserGRSAtAddressStorage', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributionScore', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'contributionStart', values?: undefined): string;
encodeFunctionData(functionFragment: 'exitModel', values?: undefined): string;
encodeFunctionData(functionFragment: 'feedback', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'freeriderPenalty', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllAccuraciesAbout', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAllPreviousAccuraciesAndLosses', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'isContributionRoundDone', values?: undefined): string;
encodeFunctionData(functionFragment: 'isFeedBackRoundDone', values?: undefined): string;
encodeFunctionData(functionFragment: 'max_collateral', values?: undefined): string;
encodeFunctionData(functionFragment: 'min_collateral', values?: undefined): string;
encodeFunctionData(functionFragment: 'min_rounds', values?: undefined): string;
encodeFunctionData(functionFragment: 'modelHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'nrOfContributionScores', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nrOfParticipants', values?: undefined): string;
encodeFunctionData(functionFragment: 'nrOfProvidedHashedWeights', values?: undefined): string;
encodeFunctionData(functionFragment: 'participants', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'prev_accs', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'prev_losses', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'provideHashedWeights', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'punishfactor', values?: undefined): string;
encodeFunctionData(functionFragment: 'punishfactorContrib', values?: undefined): string;
encodeFunctionData(functionFragment: 'register()', values?: undefined): string;
encodeFunctionData(functionFragment: 'register(address)', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerSlot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rewardLeft', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPerRound', values?: undefined): string;
encodeFunctionData(functionFragment: 'round', values?: undefined): string;
encodeFunctionData(functionFragment: 'roundStart', values?: undefined): string;
encodeFunctionData(functionFragment: 'secretOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settle', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitContributionScore', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitFeedbackBytes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'submitFeedbackBytesAndAccuracies', values: [BytesLike, BigNumberish[], BigNumberish[], BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'testing', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalReward', values?: undefined): string;
encodeFunctionData(functionFragment: 'users', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votedPositiveFor', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'votesPerRound', values?: undefined): string;
encodeFunctionData(functionFragment: 'weightsOf', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: '__isPunished', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '__testInitSettleState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_getUserGRSAtAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_setUserGRSAtAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_setUserGRSAtAddressStorage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributionScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributionStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exitModel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feedback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freeriderPenalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllAccuraciesAbout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllPreviousAccuraciesAndLosses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isContributionRoundDone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFeedBackRoundDone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'max_collateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'min_collateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'min_rounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'modelHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nrOfContributionScores', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nrOfParticipants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nrOfProvidedHashedWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prev_accs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prev_losses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provideHashedWeights', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'punishfactor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'punishfactorContrib', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register(address)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardLeft', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPerRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'round', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roundStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'secretOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitContributionScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFeedbackBytes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFeedbackBytesAndAccuracies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'testing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'users', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votedPositiveFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votesPerRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weightsOf', data: BytesLike): Result;
  }

  
    export namespace ContributionScoreSubmittedEvent {
      export type InputTuple = [user: AddressLike, contributionScore: BigNumberish];
      export type OutputTuple = [user: string, contributionScore: bigint];
      export interface OutputObject {user: string, contributionScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DebugUserEvent {
      export type InputTuple = [addr: AddressLike, weightedContribScore: BigNumberish, globalReputationScore: BigNumberish, roundReputation: BigNumberish, nrOfRoundsParticipated: BigNumberish, nrOfVotesFromUser: BigNumberish, isPunished: boolean, isRegistered: boolean, whitelistedForRewards: boolean, isDisqualified: boolean];
      export type OutputTuple = [addr: string, weightedContribScore: bigint, globalReputationScore: bigint, roundReputation: bigint, nrOfRoundsParticipated: bigint, nrOfVotesFromUser: bigint, isPunished: boolean, isRegistered: boolean, whitelistedForRewards: boolean, isDisqualified: boolean];
      export interface OutputObject {addr: string, weightedContribScore: bigint, globalReputationScore: bigint, roundReputation: bigint, nrOfRoundsParticipated: bigint, nrOfVotesFromUser: bigint, isPunished: boolean, isRegistered: boolean, whitelistedForRewards: boolean, isDisqualified: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisqualificationEvent {
      export type InputTuple = [victim: AddressLike, roundScore: BigNumberish, loss: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [victim: string, roundScore: bigint, loss: bigint, newReputation: bigint];
      export interface OutputObject {victim: string, roundScore: bigint, loss: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EndRoundEvent {
      export type InputTuple = [round: BigNumberish, validVotes: BigNumberish, sumOfWeightedContribScore: BigNumberish, totalPunishment: BigNumberish];
      export type OutputTuple = [round: bigint, validVotes: bigint, sumOfWeightedContribScore: bigint, totalPunishment: bigint];
      export interface OutputObject {round: bigint, validVotes: bigint, sumOfWeightedContribScore: bigint, totalPunishment: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FederatedLerningModelDeployedEvent {
      export type InputTuple = [initTS: BigNumberish, max_collateral: BigNumberish, min_collateral: BigNumberish, total_reward: BigNumberish, min_rounds: BigNumberish, freerider_fee: BigNumberish];
      export type OutputTuple = [initTS: bigint, max_collateral: bigint, min_collateral: bigint, total_reward: bigint, min_rounds: bigint, freerider_fee: bigint];
      export interface OutputObject {initTS: bigint, max_collateral: bigint, min_collateral: bigint, total_reward: bigint, min_rounds: bigint, freerider_fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeedbackEvent {
      export type InputTuple = [target: AddressLike, user: AddressLike, globalReputation: BigNumberish, newroundReputation: BigNumberish];
      export type OutputTuple = [target: string, user: string, globalReputation: bigint, newroundReputation: bigint];
      export interface OutputObject {target: string, user: string, globalReputation: bigint, newroundReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassivPunishmentEvent {
      export type InputTuple = [victim: AddressLike, roundScore: BigNumberish, loss: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [victim: string, roundScore: bigint, loss: bigint, newReputation: bigint];
      export interface OutputObject {victim: string, roundScore: bigint, loss: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PunishmentEvent {
      export type InputTuple = [victim: AddressLike, roundScore: BigNumberish, loss: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [victim: string, roundScore: bigint, loss: bigint, newReputation: bigint];
      export interface OutputObject {victim: string, roundScore: bigint, loss: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegisteredEvent {
      export type InputTuple = [user: AddressLike, reputationValue: BigNumberish, totalCollateral: BigNumberish, numberOfContributers: BigNumberish];
      export type OutputTuple = [user: string, reputationValue: bigint, totalCollateral: bigint, numberOfContributers: bigint];
      export interface OutputObject {user: string, reputationValue: bigint, totalCollateral: bigint, numberOfContributers: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardEvent {
      export type InputTuple = [user: AddressLike, roundScore: BigNumberish, win: BigNumberish, newReputation: BigNumberish];
      export type OutputTuple = [user: string, roundScore: bigint, win: bigint, newReputation: bigint];
      export interface OutputObject {user: string, roundScore: bigint, win: bigint, newReputation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface OpenFLModelHarness extends BaseContract {
    
    connect(runner?: ContractRunner | null): OpenFLModelHarness;
    waitForDeployment(): Promise<this>;

    interface: OpenFLModelHarnessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    __isPunished: TypedContractMethod<
      [userAddr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    __testInitSettleState: TypedContractMethod<
      [p: OpenFLModelHarness.InitParamsStruct, ],
      [void],
      'nonpayable'
    >
    

    
    _getUserGRSAtAddress: TypedContractMethod<
      [userAddr: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    _setUserGRSAtAddress: TypedContractMethod<
      [userAddr: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    _setUserGRSAtAddressStorage: TypedContractMethod<
      [userAddr: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contributionScore: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    contributionStart: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    exitModel: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    feedback: TypedContractMethod<
      [target: AddressLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    freeriderPenalty: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAllAccuraciesAbout: TypedContractMethod<
      [target: AddressLike, ],
      [[string[], bigint[], bigint[]] & {voters: string[], accuracies: bigint[], losses: bigint[] }],
      'view'
    >
    

    
    getAllPreviousAccuraciesAndLosses: TypedContractMethod<
      [],
      [[bigint[], bigint[]] & {previous_accuracies: bigint[], previous_losses: bigint[] }],
      'view'
    >
    

    
    getUser: TypedContractMethod<
      [u: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean]],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isContributionRoundDone: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isFeedBackRoundDone: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    max_collateral: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    min_collateral: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    min_rounds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    modelHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nrOfContributionScores: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    nrOfParticipants: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nrOfProvidedHashedWeights: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    participants: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    prev_accs: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    prev_losses: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    provideHashedWeights: TypedContractMethod<
      [hashedWeights: BytesLike, salt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    punishfactor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    punishfactorContrib: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    "register()": TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    "register(address)": TypedContractMethod<
      [initiator: AddressLike, ],
      [void],
      'payable'
    >
    

    
    registerSlot: TypedContractMethod<
      [_secret: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewardLeft: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardPerRound: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    round: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    roundStart: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    secretOf: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    settle: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    submitContributionScore: TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitFeedbackBytes: TypedContractMethod<
      [raw: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitFeedbackBytesAndAccuracies: TypedContractMethod<
      [raw: BytesLike, accuracies: BigNumberish[], losses: BigNumberish[], prev_acc: BigNumberish, prev_loss: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    testing: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    totalReward: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    users: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, string, bigint, bigint, boolean, boolean, boolean, boolean] & {weightedContribScore: bigint, globalReputationScore: bigint, roundReputation: bigint, addr: string, nrOfRoundsParticipated: bigint, nrOfVotesFromUser: bigint, isPunished: boolean, isRegistered: boolean, whitelistedForRewards: boolean, isDisqualified: boolean }],
      'view'
    >
    

    
    votedPositiveFor: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    votesPerRound: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    weightsOf: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: '__isPunished'): TypedContractMethod<
      [userAddr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: '__testInitSettleState'): TypedContractMethod<
      [p: OpenFLModelHarness.InitParamsStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: '_getUserGRSAtAddress'): TypedContractMethod<
      [userAddr: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: '_setUserGRSAtAddress'): TypedContractMethod<
      [userAddr: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: '_setUserGRSAtAddressStorage'): TypedContractMethod<
      [userAddr: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contributionScore'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contributionStart'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'exitModel'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feedback'): TypedContractMethod<
      [target: AddressLike, score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'freeriderPenalty'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAllAccuraciesAbout'): TypedContractMethod<
      [target: AddressLike, ],
      [[string[], bigint[], bigint[]] & {voters: string[], accuracies: bigint[], losses: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getAllPreviousAccuraciesAndLosses'): TypedContractMethod<
      [],
      [[bigint[], bigint[]] & {previous_accuracies: bigint[], previous_losses: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getUser'): TypedContractMethod<
      [u: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean]],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isContributionRoundDone'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isFeedBackRoundDone'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'max_collateral'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'min_collateral'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'min_rounds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'modelHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nrOfContributionScores'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nrOfParticipants'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nrOfProvidedHashedWeights'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'participants'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'prev_accs'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'prev_losses'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'provideHashedWeights'): TypedContractMethod<
      [hashedWeights: BytesLike, salt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'punishfactor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'punishfactorContrib'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'register()'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'register(address)'): TypedContractMethod<
      [initiator: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'registerSlot'): TypedContractMethod<
      [_secret: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardLeft'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardPerRound'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'round'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'roundStart'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'secretOf'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'settle'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitContributionScore'): TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFeedbackBytes'): TypedContractMethod<
      [raw: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFeedbackBytesAndAccuracies'): TypedContractMethod<
      [raw: BytesLike, accuracies: BigNumberish[], losses: BigNumberish[], prev_acc: BigNumberish, prev_loss: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'testing'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalReward'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'users'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, string, bigint, bigint, boolean, boolean, boolean, boolean] & {weightedContribScore: bigint, globalReputationScore: bigint, roundReputation: bigint, addr: string, nrOfRoundsParticipated: bigint, nrOfVotesFromUser: bigint, isPunished: boolean, isRegistered: boolean, whitelistedForRewards: boolean, isDisqualified: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'votedPositiveFor'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votesPerRound'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weightsOf'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ContributionScoreSubmitted'): TypedContractEvent<ContributionScoreSubmittedEvent.InputTuple, ContributionScoreSubmittedEvent.OutputTuple, ContributionScoreSubmittedEvent.OutputObject>;
getEvent(key: 'DebugUser'): TypedContractEvent<DebugUserEvent.InputTuple, DebugUserEvent.OutputTuple, DebugUserEvent.OutputObject>;
getEvent(key: 'Disqualification'): TypedContractEvent<DisqualificationEvent.InputTuple, DisqualificationEvent.OutputTuple, DisqualificationEvent.OutputObject>;
getEvent(key: 'EndRound'): TypedContractEvent<EndRoundEvent.InputTuple, EndRoundEvent.OutputTuple, EndRoundEvent.OutputObject>;
getEvent(key: 'FederatedLerningModelDeployed'): TypedContractEvent<FederatedLerningModelDeployedEvent.InputTuple, FederatedLerningModelDeployedEvent.OutputTuple, FederatedLerningModelDeployedEvent.OutputObject>;
getEvent(key: 'Feedback'): TypedContractEvent<FeedbackEvent.InputTuple, FeedbackEvent.OutputTuple, FeedbackEvent.OutputObject>;
getEvent(key: 'PassivPunishment'): TypedContractEvent<PassivPunishmentEvent.InputTuple, PassivPunishmentEvent.OutputTuple, PassivPunishmentEvent.OutputObject>;
getEvent(key: 'Punishment'): TypedContractEvent<PunishmentEvent.InputTuple, PunishmentEvent.OutputTuple, PunishmentEvent.OutputObject>;
getEvent(key: 'Registered'): TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
getEvent(key: 'Reward'): TypedContractEvent<RewardEvent.InputTuple, RewardEvent.OutputTuple, RewardEvent.OutputObject>;

    filters: {
      
      'ContributionScoreSubmitted(address,int256)': TypedContractEvent<ContributionScoreSubmittedEvent.InputTuple, ContributionScoreSubmittedEvent.OutputTuple, ContributionScoreSubmittedEvent.OutputObject>;
      ContributionScoreSubmitted: TypedContractEvent<ContributionScoreSubmittedEvent.InputTuple, ContributionScoreSubmittedEvent.OutputTuple, ContributionScoreSubmittedEvent.OutputObject>;
    

      'DebugUser(address,int256,uint256,int256,uint8,uint8,bool,bool,bool,bool)': TypedContractEvent<DebugUserEvent.InputTuple, DebugUserEvent.OutputTuple, DebugUserEvent.OutputObject>;
      DebugUser: TypedContractEvent<DebugUserEvent.InputTuple, DebugUserEvent.OutputTuple, DebugUserEvent.OutputObject>;
    

      'Disqualification(address,int256,uint256,uint256)': TypedContractEvent<DisqualificationEvent.InputTuple, DisqualificationEvent.OutputTuple, DisqualificationEvent.OutputObject>;
      Disqualification: TypedContractEvent<DisqualificationEvent.InputTuple, DisqualificationEvent.OutputTuple, DisqualificationEvent.OutputObject>;
    

      'EndRound(uint8,uint8,uint256,uint256)': TypedContractEvent<EndRoundEvent.InputTuple, EndRoundEvent.OutputTuple, EndRoundEvent.OutputObject>;
      EndRound: TypedContractEvent<EndRoundEvent.InputTuple, EndRoundEvent.OutputTuple, EndRoundEvent.OutputObject>;
    

      'FederatedLerningModelDeployed(uint256,uint256,uint256,uint256,uint8,uint256)': TypedContractEvent<FederatedLerningModelDeployedEvent.InputTuple, FederatedLerningModelDeployedEvent.OutputTuple, FederatedLerningModelDeployedEvent.OutputObject>;
      FederatedLerningModelDeployed: TypedContractEvent<FederatedLerningModelDeployedEvent.InputTuple, FederatedLerningModelDeployedEvent.OutputTuple, FederatedLerningModelDeployedEvent.OutputObject>;
    

      'Feedback(address,address,uint256,int256)': TypedContractEvent<FeedbackEvent.InputTuple, FeedbackEvent.OutputTuple, FeedbackEvent.OutputObject>;
      Feedback: TypedContractEvent<FeedbackEvent.InputTuple, FeedbackEvent.OutputTuple, FeedbackEvent.OutputObject>;
    

      'PassivPunishment(address,int256,uint256,uint256)': TypedContractEvent<PassivPunishmentEvent.InputTuple, PassivPunishmentEvent.OutputTuple, PassivPunishmentEvent.OutputObject>;
      PassivPunishment: TypedContractEvent<PassivPunishmentEvent.InputTuple, PassivPunishmentEvent.OutputTuple, PassivPunishmentEvent.OutputObject>;
    

      'Punishment(address,int256,uint256,uint256)': TypedContractEvent<PunishmentEvent.InputTuple, PunishmentEvent.OutputTuple, PunishmentEvent.OutputObject>;
      Punishment: TypedContractEvent<PunishmentEvent.InputTuple, PunishmentEvent.OutputTuple, PunishmentEvent.OutputObject>;
    

      'Registered(address,uint256,uint256,uint256)': TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
      Registered: TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
    

      'Reward(address,int256,uint256,uint256)': TypedContractEvent<RewardEvent.InputTuple, RewardEvent.OutputTuple, RewardEvent.OutputObject>;
      Reward: TypedContractEvent<RewardEvent.InputTuple, RewardEvent.OutputTuple, RewardEvent.OutputObject>;
    
    };
  }