/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'OpenFLManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OpenFLManager__factory>
getContractFactory(name: 'OpenFLModel', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OpenFLModel__factory>
getContractFactory(name: 'OpenFLModelHarness', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OpenFLModelHarness__factory>

  getContractAt(name: 'OpenFLManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OpenFLManager>
getContractAt(name: 'OpenFLModel', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OpenFLModel>
getContractAt(name: 'OpenFLModelHarness', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OpenFLModelHarness>

  deployContract(name: 'OpenFLManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLManager>
deployContract(name: 'OpenFLModel', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLModel>
deployContract(name: 'OpenFLModelHarness', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLModelHarness>

  deployContract(name: 'OpenFLManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLManager>
deployContract(name: 'OpenFLModel', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLModel>
deployContract(name: 'OpenFLModelHarness', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OpenFLModelHarness>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  