/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OpenFLManagerInterface extends Interface {
    getFunction(nameOrSignature: "ModelCountOf" | "ModelOf" | "deployModel"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'ModelCountOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'ModelOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployModel', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ModelCountOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ModelOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployModel', data: BytesLike): Result;
  }

  

  export interface OpenFLManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): OpenFLManager;
    waitForDeployment(): Promise<this>;

    interface: OpenFLManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ModelCountOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    ModelOf: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deployModel: TypedContractMethod<
      [_modelHash: BytesLike, _min_collateral: BigNumberish, _max_collateral: BigNumberish, _reward: BigNumberish, _min_rounds: BigNumberish, _punishfactor: BigNumberish, _punishfactorContrib: BigNumberish, _freeriderPenalty: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ModelCountOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ModelOf'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deployModel'): TypedContractMethod<
      [_modelHash: BytesLike, _min_collateral: BigNumberish, _max_collateral: BigNumberish, _reward: BigNumberish, _min_rounds: BigNumberish, _punishfactor: BigNumberish, _punishfactorContrib: BigNumberish, _freeriderPenalty: BigNumberish, ],
      [void],
      'payable'
    >;

    

    filters: {
      
    };
  }